# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-13 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('humidity', models.FloatField()),
                ('temperature', models.FloatField()),
                ('is_pan_turn', models.BooleanField()),
            ],
        ),
    ]
